### ISSUE TITLE
Clear local storage on exit

### ISSUE THREAD

**Issue by darknight7** [oyenamit/web-storage-viewer#1]
It would be _super nice_ if you could add a flag to automatically remove all stored data on browser exit/start.

**Comment by oyenamit** [comment]
If you are looking for such fine control over cookies and web storage, you might want to explore existing add-ons like [Cookie Keeper](https://addons.mozilla.org/en-US/firefox/addon/cookiekeeper) and [Cookie Controller](https://addons.mozilla.org/en-US/firefox/addon/cookie-controller).

These deal with cookies as well as local storage.

**Comment by darknight7** [comment]
Thanks, cookie keeper seems to be the way to go, I was fooled by the name.
